
services:
  service_a:
    build: ./service_a
    ports:
      - "8080:8080"
    depends_on:
      - service_b
      - zipkin
    environment:
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"

  service_b:
    build: ./service_b
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
    environment:
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"